// data.js

export const data = {
  tickets: [
    {
      id: "CAM-1",
      title: "Update User Profile Page UI",
      tag: ["Feature request"],
      userId: "usr-1",
      status: "Todo",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 4,
    },
    {
      id: "CAM-2",

      title:
        "Add Multi-Language Support - Enable multi-language support within the application.",
      tag: ["Feature Request"],
      userId: "usr-2",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 3,
    },
    {
      id: "CAM-3",
      title: "Optimize Database Queries for Performance",
      tag: ["Feature Request"],
      userId: "usr-2",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 1,
    },
    {
      id: "CAM-4",
      title: "Implement Email Notification System",
      tag: ["Feature Request"],
      userId: "usr-1",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 3,
    },
    {
      id: "CAM-5",
      title: "Enhance Search Functionality",
      tag: ["Feature Request"],
      userId: "usr-5",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 0,
    },
    {
      id: "CAM-6",
      title: "Third-Party Payment Gateway",
      tag: ["Feature Request"],
      userId: "usr-2",
      status: "Todo",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 1,
    },
    {
      id: "CAM-7",
      title: "Create Onboarding Tutorial for New Users",
      tag: ["Feature Request"],
      userId: "usr-1",
      status: "Done",
      statusIcon: "/svg/Done.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 2,
    },
    {
      id: "CAM-8",
      title: "Implement Role-Based Access Control (RBAC)",
      tag: ["Feature Request"],
      userId: "usr-3",
      status: "In progress",
      statusIcon: "/svg/in-progress.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 3,
    },
    {
      id: "CAM-9",
      title: "Upgrade Server Infrastructure",
      tag: ["Feature Request"],
      userId: "usr-5",
      statusIcon: "/svg/To-do.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      status: "Todo",
      priority: 2,
    },
    {
      id: "CAM-10",
      tag: ["Feature Request"],
      userId: "usr-4",
      status: "Canceled",
      statusIcon: "/svg/Cancelled.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 0,
    },
    {
      id: "CAM-10",
      title: "Conduct Security Assessment",
      tag: ["Feature Request"],
      userId: "usr-4",
      status: "Done",
      statusIcon: "/svg/Done.svg",
      statusIcon1: "/svg/3 dot menu.svg",
      priority: 1,
    },
  ],
  users: [
    { id: "usr-1", name: "Anoop Sharma", available: false },
    { id: "usr-2", name: "Yogesh", available: true },
    { id: "usr-3", name: "Shankar Kumar", available: true },
    { id: "usr-4", name: "Ramesh", available: true },
    { id: "usr-5", name: "Suresh", available: true },
  ],
};
